### PR TITLE
Correct the preference of environment variables

### PR DESCRIPTION
**Pull request by grahamhar**
As per https://github.com/aws/aws-cli/issues/2597 the AWS_PROFILE should take preference over AWS_DEFAULT_PROFILE

### CODE REVIEW

**Comment by strongoose** [comment]
I wonder if it would be better just to check whether those variables are set and let boto handle the rest, i.e.
```
def parse_args():
    ...
    if os.getenv('AWS_PROFILE', os.getenv('AWS_DEFAULT_PROFILE')):
        profile = None
    elif len(argv) >= 3:
        profile = argv.pop(1)
    else:
        print("Usage: %s [profile] command [args]" % os.path.basename(argv[0]))
        quit(1)
    ...
def main():
    ...
    if profile:
        session = botocore.session.Session(profile=profile)
    else:
        session = botocore.session.Session()
```

**Comment by strongoose** [comment]
Happy to do a PR to that effect if that sounds good.

**Comment by grahamhar** [comment]
I think letting boto handle it is cleaner. If we move to using an named argument  rather than a positional one then the profile could just be set if that option is there. This assumes if you have set the option you want to override the env vars.

**Comment by grahamhar** [comment]
Looking at the docs it can be made even simpler as the default value for profile in botocore.session.Session is None. We can then just make a default value of None on the new argument we introduce for profile.

**Comment by grahamhar** [comment]
Closing for now as proposing a move to argparse.

**Pull request closed without merging**
