### PR TITLE
Fix environment variable unsetting not working on Windows

### PR DESCRIPTION
**Pull request by DewaldDeJager**
A colleague of mine was facing issues with the script on Windows with Python 3.7. `os.unsetenv` was not working.

From the [Python docs](https://docs.python.org/3/library/os.html#os.unsetenv):
> When unsetenv() is supported, deletion of items in os.environ is automatically translated into a corresponding call to unsetenv(); however, calls to unsetenv() don’t update os.environ, so it is actually preferable to delete items of os.environ.

### CODE REVIEW

**Comment by DewaldDeJager** [comment]
@jrstarke Have you had a chance to look at this yet?

Travis is failing because of something silly. Trying to re-run the build but it seems I can't.

**Comment by jrstarke** [comment]
@DewaldDeJager Looks like the tests are failing on this PR (https://travis-ci.org/jrstarke/aws-profile/builds/523454183?utm_source=github_status&utm_medium=notification)

**Comment by jrstarke** [comment]
Looks like the builds are just failing in general. I'll look into why the builds are failing.

**Comment by DewaldDeJager** [comment]
> Looks like the builds are just failing in general. I'll look into why the builds are failing.

@jrstarke Any update on this? A lot of my colleagues are impacted by this and it would be way easier if this fix was published officially.

Thank you. I appreciate your time. Let me know if there is anything I can help with.

**Comment by jrstarke** [comment]
@entelect I've forced a rebuild of your pr. A while back I fixed the master builds, and started running tests nightly to detect issues

**Comment by DewaldDeJager** [comment]
> @entelect I've forced a rebuild of your pr. A while back I fixed the master builds, and started running tests nightly to detect issues

@jrstarke Thank you for triggering the build. I see the builds for some of the versions are failing with this error:
```
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 3.0.7 (/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages), Requirement.parse('pytest>=3.6'))!
```
Do you know what the cause could be?

**Comment by jrstarke** [comment]
@DewaldDeJager Looks like there is a merge conflict with master. It's possible that the issue was fixed on master, but not on your branch.

**Comment by DewaldDeJager** [comment]
> @DewaldDeJager Looks like there is a merge conflict with master. It's possible that the issue was fixed on master, but not on your branch.

The problem here is that I thought you had abandoned the repository, so I deleted my fork. There is no way for me to merge the latest `master` in. I will re-fork and re-apply the changes before making another PR.

**Pull request closed without merging**
